export const INITIAL_HCPS = [
  {
    id: "hcp-1",
    name: "Dr. Rahul Sharma",
    qualification: "MD, DM (Cardiology), FACC",
    specialty: "Cardiology",
    hospital: "Apollo Hospital",
    department: "Department of Interventional Cardiology",
    city: "New Delhi",
    state: "Delhi",
    tier: "KOL",
    priority: "High",
    status: "Active",
    email: "dr.rahul.sharma@apollohospitals.com",
    phone: "+91 98112 34567",
    preferredTime: "Tuesdays & Thursdays, 2:00 PM - 4:00 PM",
    prescribingPotential: "Very High (₹25L+/month)",
    productsOfInterest: ["CardioPlus 50mg", "GlucoCare Duo"],
    lastVisit: "2026-07-14",
    nextFollowUp: "2026-07-21",
    interactionCount: 14,
    notes: "Key opinion leader for cardiovascular clinical trials. Very receptive to new clinical trial data on CardioPlus outcome studies. Prefers concise scientific abstracts.",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "hcp-2",
    name: "Dr. Priya Mehta",
    qualification: "MBBS, MD (Neurology), DNB",
    specialty: "Neurology",
    hospital: "Fortis Memorial Research Institute",
    department: "Neurosciences & Stroke Unit",
    city: "Gurugram",
    state: "Haryana",
    tier: "Tier 1",
    priority: "High",
    status: "Active",
    email: "priya.mehta@fortishealthcare.com",
    phone: "+91 98234 56789",
    preferredTime: "Mondays & Wednesdays, 11:00 AM - 1:00 PM",
    prescribingPotential: "High (₹18L+/month)",
    productsOfInterest: ["NeuroGuard XR"],
    lastVisit: "2026-07-12",
    nextFollowUp: "2026-07-19",
    interactionCount: 9,
    notes: "Focuses on post-stroke neurological rehabilitation and epilepsy management. Requested comparative bio-availability study for NeuroGuard XR.",
    avatar: "https://images.unsplash.com/photo-1594824813591-9657b98ec517?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "hcp-3",
    name: "Dr. Amit Verma",
    qualification: "MS (Orthopaedics), M.Ch (Joint Replacement)",
    specialty: "Orthopedics",
    hospital: "Medanta - The Medicity",
    department: "Orthopedic & Joint Reconstruction",
    city: "Gurugram",
    state: "Haryana",
    tier: "Tier 1",
    priority: "High",
    status: "Active",
    email: "amit.verma@medanta.org",
    phone: "+91 98450 12345",
    preferredTime: "Fridays, 3:00 PM - 5:30 PM",
    prescribingPotential: "High (₹15L+/month)",
    productsOfInterest: ["OrthoFlex Plus"],
    lastVisit: "2026-07-10",
    nextFollowUp: "2026-07-24",
    interactionCount: 11,
    notes: "High-volume robotic joint surgeon. Currently prescribing competitor brand OrthoMax but noted excellent patient feedback on OrthoFlex Plus recovery times.",
    avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "hcp-4",
    name: "Dr. Sneha Kapoor",
    qualification: "MD (Pediatrics), FIAP",
    specialty: "Pediatrics",
    hospital: "Max Super Speciality Hospital",
    department: "Pediatric Critical Care & Neonatology",
    city: "New Delhi",
    state: "Delhi",
    tier: "Tier 2",
    priority: "Medium",
    status: "Active",
    email: "dr.sneha@maxhealthcare.com",
    phone: "+91 97123 45678",
    preferredTime: "Saturdays, 10:00 AM - 12:00 PM",
    prescribingPotential: "Medium (₹8L+/month)",
    productsOfInterest: ["RespiraEase Inhaler", "GlucoCare Duo"],
    lastVisit: "2026-07-08",
    nextFollowUp: "2026-07-22",
    interactionCount: 6,
    notes: "Interested in pediatric dosage guidelines and palatable syrup formulations. Requested 20 starter patient kits.",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "hcp-5",
    name: "Dr. Rajesh Kulkarni",
    qualification: "MD, DM (Medical Oncology)",
    specialty: "Oncology",
    hospital: "AIIMS (All India Institute of Medical Sciences)",
    department: "Department of Medical Oncology",
    city: "New Delhi",
    state: "Delhi",
    tier: "KOL",
    priority: "High",
    status: "Active",
    email: "rajesh.kulkarni@aiims.edu",
    phone: "+91 98333 11223",
    preferredTime: "Wednesdays, 4:00 PM - 5:00 PM",
    prescribingPotential: "Very High (₹35L+/month)",
    productsOfInterest: ["OncoShield 250"],
    lastVisit: "2026-07-06",
    nextFollowUp: "2026-07-20",
    interactionCount: 16,
    notes: "Head of AIIMS Thoracic Oncology division. Key committee member for institutional procurement. Strongly interested in our patient assistance program.",
    avatar: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "hcp-6",
    name: "Dr. Ananya Sengupta",
    qualification: "MD (Endocrinology), FACE",
    specialty: "Endocrinology",
    hospital: "Manipal Hospital",
    department: "Diabetes & Endocrine Sciences",
    city: "Bengaluru",
    state: "Karnataka",
    tier: "Tier 1",
    priority: "High",
    status: "Active",
    email: "ananya.sengupta@manipalhospitals.com",
    phone: "+91 99001 23456",
    preferredTime: "Thursdays, 1:00 PM - 3:00 PM",
    prescribingPotential: "High (₹16L+/month)",
    productsOfInterest: ["GlucoCare Duo"],
    lastVisit: "2026-07-05",
    nextFollowUp: "2026-07-18",
    interactionCount: 8,
    notes: "Active speaker in South Asia Diabetes Summit. Emphasizes HbA1c reduction without hypoglycemia risk.",
    avatar: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "hcp-7",
    name: "Dr. Vikramaditya Rao",
    qualification: "MD, DNB (Gastroenterology)",
    specialty: "Gastroenterology",
    hospital: "Apollo Hospital",
    department: "Institute of Liver & Digestive Sciences",
    city: "Chennai",
    state: "Tamil Nadu",
    tier: "Tier 2",
    priority: "Medium",
    status: "Active",
    email: "v.rao@apollohospitals.com",
    phone: "+91 98400 98765",
    preferredTime: "Mondays, 2:30 PM - 4:00 PM",
    prescribingPotential: "Medium (₹10L+/month)",
    productsOfInterest: ["GastroShield 40mg"],
    lastVisit: "2026-06-28",
    nextFollowUp: "2026-07-25",
    interactionCount: 5,
    notes: "Specializes in acid-peptic disorders and GERD management. Requested patient education brochures for GastroShield.",
    avatar: "https://images.unsplash.com/photo-1622902046580-2b47f47f5471?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "hcp-8",
    name: "Dr. Meenakshi Iyer",
    qualification: "MD (Pulmonology), FCCP",
    specialty: "Pulmonology",
    hospital: "Fortis Hospital",
    department: "Chest Medicine & Sleep Disorders",
    city: "Mumbai",
    state: "Maharashtra",
    tier: "Tier 2",
    priority: "Medium",
    status: "Follow-up",
    email: "meenakshi.iyer@fortis.in",
    phone: "+91 98200 54321",
    preferredTime: "Tuesdays, 12:00 PM - 2:00 PM",
    prescribingPotential: "Medium (₹11L+/month)",
    productsOfInterest: ["RespiraEase Inhaler"],
    lastVisit: "2026-06-25",
    nextFollowUp: "2026-07-16",
    interactionCount: 4,
    notes: "Interested in device ergonomics and inhaler dosage counter visibility for elderly COPD patients.",
    avatar: "https://images.unsplash.com/photo-1594824813636-f0f37aa5905d?w=150&auto=format&fit=crop&q=80"
  }
];

export const PRODUCTS_CATALOG = [
  { id: "prod-1", name: "CardioPlus 50mg", category: "Cardiovascular", indication: "Hypertension & Heart Failure", formula: "Metoprolol Succinate + Telmisartan", status: "Primary Focus" },
  { id: "prod-2", name: "NeuroGuard XR", category: "Neurology", indication: "Neuropathic Pain & Post-Stroke Recovery", formula: "Pregabalin + Methylcobalamin XR", status: "Growth Driver" },
  { id: "prod-3", name: "OrthoFlex Plus", category: "Orthopedics", indication: "Osteoarthritis & Joint Mobility", formula: "Glucosamine Sulfate + Collagen Peptides", status: "Mature" },
  { id: "prod-4", name: "OncoShield 250", category: "Oncology", indication: "Targeted Oncology Therapy", formula: "Erlotinib Hydrochloride 250mg", status: "High Priority" },
  { id: "prod-5", name: "GlucoCare Duo", category: "Endocrinology", indication: "Type 2 Diabetes Mellitus", formula: "Dapagliflozin + Metformin SR", status: "Growth Driver" },
  { id: "prod-6", name: "RespiraEase Inhaler", category: "Pulmonology", indication: "Asthma & Severe COPD", formula: "Budesonide + Formoterol Fumarate", status: "Standard" },
  { id: "prod-7", name: "GastroShield 40mg", category: "Gastroenterology", indication: "GERD & Gastric Ulcers", formula: "Esomeprazole Magnesium 40mg", status: "Standard" }
];

export const HOSPITALS = [
  "Apollo Hospital",
  "Fortis Memorial Research Institute",
  "Medanta - The Medicity",
  "Max Super Speciality Hospital",
  "AIIMS (All India Institute of Medical Sciences)",
  "Manipal Hospital"
];

export const SPECIALTIES = [
  "Cardiology",
  "Neurology",
  "Orthopedics",
  "Pediatrics",
  "Oncology",
  "Endocrinology",
  "Gastroenterology",
  "Pulmonology"
];

export const INITIAL_INTERACTIONS = [
  {
    id: "int-101",
    hcpId: "hcp-1",
    doctorName: "Dr. Rahul Sharma",
    specialty: "Cardiology",
    hospital: "Apollo Hospital",
    date: "2026-07-14",
    time: "02:30 PM",
    visitType: "In-Person Detailing",
    products: ["CardioPlus 50mg", "GlucoCare Duo"],
    rawNotes: "Detailed the Phase-3 REDUCE-HF trial data showing 24% reduction in CV re-hospitalizations. Dr. Sharma expressed high satisfaction with tolerability profile. Requested 15 patient trial packs and invited us to sponsor a hospital CME in August.",
    aiSummary: {
      doctorName: "Dr. Rahul Sharma",
      hospital: "Apollo Hospital",
      productsDiscussed: ["CardioPlus 50mg", "GlucoCare Duo"],
      summary: "Detailed the Phase-3 REDUCE-HF trial data showing significant CV hospitalization reduction. Doctor expressed positive reception regarding tolerability and asked for patient samples.",
      sentiment: "Positive",
      followUpAction: "Deliver 15 CardioPlus trial samples by Friday and draft sponsorship proposal for August cardiology CME.",
      confidenceScore: "96%"
    },
    status: "Completed",
    sentiment: "Positive",
    followUpDate: "2026-07-21"
  },
  {
    id: "int-102",
    hcpId: "hcp-2",
    doctorName: "Dr. Priya Mehta",
    specialty: "Neurology",
    hospital: "Fortis Memorial Research Institute",
    date: "2026-07-12",
    time: "11:45 AM",
    visitType: "Clinic Round",
    products: ["NeuroGuard XR"],
    rawNotes: "Discussed NeuroGuard XR once-daily dosing advantages over immediate-release generics. Dr. Mehta raised concerns about patient compliance with bedtime dosing and price differential.",
    aiSummary: {
      doctorName: "Dr. Priya Mehta",
      hospital: "Fortis Memorial Research Institute",
      productsDiscussed: ["NeuroGuard XR"],
      summary: "Reviewed sustained-release formulation benefits for diabetic neuropathy patients. Discussed pricing concerns and bedtime tolerability.",
      sentiment: "Neutral",
      followUpAction: "Provide comparative pharmacokinetics paper and price-per-day patient savings breakdown.",
      confidenceScore: "91%"
    },
    status: "Completed",
    sentiment: "Neutral",
    followUpDate: "2026-07-19"
  },
  {
    id: "int-103",
    hcpId: "hcp-5",
    doctorName: "Dr. Rajesh Kulkarni",
    specialty: "Oncology",
    hospital: "AIIMS",
    date: "2026-07-06",
    time: "04:15 PM",
    visitType: "Grand Round / Scientific Exchange",
    products: ["OncoShield 250"],
    rawNotes: "Presented 5-year overall survival Kaplan-Meier curves for OncoShield in EGFR-mutant NSCLC. Dr. Kulkarni confirmed that our drug is being added to the institutional formulary review agenda next month.",
    aiSummary: {
      doctorName: "Dr. Rajesh Kulkarni",
      hospital: "AIIMS",
      productsDiscussed: ["OncoShield 250"],
      summary: "High-impact scientific exchange on 5-year OS data. Key institutional approval milestone achieved with formulary inclusion pending.",
      sentiment: "Positive",
      followUpAction: "Submit formal dossier to AIIMS Pharmacy and Therapeutics (P&T) committee by July 20.",
      confidenceScore: "98%"
    },
    status: "Completed",
    sentiment: "Positive",
    followUpDate: "2026-07-20"
  }
];

export const TODAY_SCHEDULE = [
  {
    id: "sch-1",
    hcpId: "hcp-1",
    doctorName: "Dr. Rahul Sharma",
    specialty: "Cardiology",
    hospital: "Apollo Hospital, Room 304",
    time: "10:30 AM",
    type: "In-Person Detailing",
    objective: "Deliver requested CardioPlus 50mg trial packs and confirm CME sponsorship dates.",
    priority: "High",
    status: "Completed"
  },
  {
    id: "sch-2",
    hcpId: "hcp-3",
    doctorName: "Dr. Amit Verma",
    specialty: "Orthopedics",
    hospital: "Medanta - The Medicity, OPD Block B",
    time: "01:15 PM",
    type: "In-Person Detailing",
    objective: "Present OrthoFlex Plus patient mobility recovery index vs competitor standard.",
    priority: "High",
    status: "In Progress"
  },
  {
    id: "sch-3",
    hcpId: "hcp-4",
    doctorName: "Dr. Sneha Kapoor",
    specialty: "Pediatrics",
    hospital: "Max Super Speciality Hospital",
    time: "03:45 PM",
    type: "Virtual Tele-detail",
    objective: "Review pediatric RespiraEase dosage titration chart and deliver starter kits.",
    priority: "Medium",
    status: "Upcoming"
  },
  {
    id: "sch-4",
    hcpId: "hcp-8",
    doctorName: "Dr. Meenakshi Iyer",
    specialty: "Pulmonology",
    hospital: "Fortis Hospital, Chest Clinic",
    time: "05:30 PM",
    type: "Phone Follow-up",
    objective: "Check patient feedback on inhaler counter readability and schedule next clinic visit.",
    priority: "Medium",
    status: "Upcoming"
  }
];

export const NOTIFICATIONS = [
  {
    id: "notif-1",
    title: "Urgent Follow-up Due Today",
    description: "Dr. Rahul Sharma requested sample delivery and CME sponsorship details.",
    time: "15m ago",
    type: "alert",
    read: false
  },
  {
    id: "notif-2",
    title: "AI CRM Insight Generated",
    description: "New prescribing pattern detected: 28% increase in GlucoCare inquiries across South Delhi territory.",
    time: "1h ago",
    type: "ai",
    read: false
  },
  {
    id: "notif-3",
    title: "Formulary Agenda Update",
    description: "OncoShield 250 scheduled for AIIMS P&T committee review on July 20.",
    time: "4h ago",
    type: "success",
    read: true
  }
];